server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://trolley.proxy.rlwy.net:41611/railway"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: xjYXOEegZJaLKhjMrbopbmsqbKOgHRav
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600